import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const playbook = readFileSync(resolve('deploy/provisioner/ansible/playbook.yml'), 'utf8')
const renewalWrapper = readFileSync(resolve('deploy/provisioner/ansible/templates/acme-renew.sh.j2'), 'utf8')
const worker = readFileSync(resolve('src/lib/node-provisioning-worker.ts'), 'utf8')

function taskBlock(name: string) {
  const start = playbook.indexOf(`    - name: ${name}`)
  const end = playbook.indexOf('\n    - name:', start + 1)
  return playbook.slice(start, end < 0 ? undefined : end)
}

describe('node provisioning playbook safety', () => {
  it('uses the pinned official SelfSteal force mode with Ansible-managed TLS', () => {
    expect(playbook).toContain('selfsteal_script_version: 2.10.0')
    expect(playbook).toContain('3594f3a4ddae19582f9dde95fdf65edeaf2892dec662eadabba55e1f8faff4c4')
    expect(playbook).toContain('- --force')
    expect(playbook).toContain('- --domain')
    expect(taskBlock('Install SelfSteal through its official force mode')).toContain('- --ssl-cert')
    expect(taskBlock('Install SelfSteal through its official force mode')).toContain('- --ssl-key')
    expect(taskBlock('Install SelfSteal through its official force mode')).not.toContain('- --acme-port')
    expect(playbook).not.toContain('ansible.builtin.expect')
  })

  it('runs the acme.sh installer from its extracted source directory', () => {
    expect(playbook).toContain('chdir: /usr/local/src/acme.sh-{{ acme_script_version }}')
    expect(taskBlock('Install base operating-system packages')).toContain('- iproute2')
  })

  it('fails closed for unknown Docker state and self-signed certificates', () => {
    expect(playbook).toContain('List all Docker container names')
    expect(playbook).toContain('existing_docker_container_names.rc == 0')
    expect(playbook).toContain("'nginx-selfsteal' not in")
    expect(playbook).toContain('(existing_docker_container_names.stdout_lines | default([]))')
    expect(playbook).not.toContain("is search('No such object')")
    expect(playbook).toContain('selfsteal_container_is_owned')
    expect(playbook).toContain('com.docker.compose.project.working_dir')
    expect(playbook).toContain('com.docker.compose.project.config_files')
    expect(playbook).toContain('Verify the mounts of the existing SelfSteal container')
    expect(playbook).toContain("selfsteal_dir + '/nginx.conf|/etc/nginx/nginx.conf'")
    expect(playbook).toContain("selfsteal_dir + '/conf.d|/etc/nginx/conf.d'")
    expect(playbook).toContain("selfsteal_dir + '/ssl|/etc/nginx/ssl'")
    expect(playbook).toContain("selfsteal_dir + '/html|/var/www/html'")
    expect(playbook).toContain('existing_selfsteal_container_mounts.rc == 0')
    expect(playbook).toContain('selfsteal_configured_domain.stdout | trim == node_fqdn')
    expect(playbook).toContain("grep -Fx -- {{ ('SELF_STEAL_DOMAIN=' + node_fqdn) | quote }}")
    expect(playbook).toContain('selfsteal_container_domain_matches | bool')
    expect(playbook).toContain('- selfsteal_container_is_owned | bool')
    expect(playbook).toContain('Reject a SelfSteal self-signed fallback certificate')
    expect(playbook).toContain('installed_certificate_subject.stdout')
    expect(playbook).toContain('installed_certificate_issuer.stdout')
    expect(playbook).toMatch(/content: \|\n\s+\{\{ provisioning_job_id \}\} \{\{ node_fqdn \}\}/)
    expect(playbook).not.toContain("selfsteal_script_sha256 }}\\n'")
  })

  it('validates incomplete SelfSteal files instead of skipping their checks', () => {
    expect(taskBlock('Validate the existing SelfSteal Compose project')).not.toContain('\n      when:')
    expect(taskBlock('Validate the existing certificate hostname')).not.toContain('\n      when:')
    expect(taskBlock('Validate the existing certificate lifetime')).not.toContain('\n      when:')
  })

  it('resumes an owned bootstrap instead of reinstalling SelfSteal on every retry', () => {
    const resumable = taskBlock('Determine whether an owned SelfSteal bootstrap can be resumed')
    expect(resumable).toContain('selfsteal_marker_is_owned')
    expect(resumable).toContain('existing_selfsteal_certificate_hostname')
    expect(resumable).toContain('existing_selfsteal_certificate_public_key')
    expect(resumable).toContain('existing_selfsteal_private_key_public_key')
    expect(taskBlock('Archive an incomplete SelfSteal installation')).toContain('- not selfsteal_is_resumable | bool')
    expect(taskBlock('Install SelfSteal through its official force mode')).toContain('- not selfsteal_is_resumable | bool')
  })

  it('issues certificates through the HTTP fallback without unsafe deployment', () => {
    const issueTask = taskBlock('Issue the trusted SelfSteal certificate through the fallback HTTP webroot')
    expect(taskBlock('Validate a cached trusted SelfSteal certificate')).toContain('-checkhost')
    expect(taskBlock('Validate a cached trusted SelfSteal certificate')).toContain('-checkend 86400')
    expect(taskBlock('Validate a cached trusted SelfSteal certificate')).toContain(".conf') | quote")
    expect(taskBlock('Validate a cached trusted SelfSteal certificate')).toContain('openssl pkey')
    expect(taskBlock('Validate a cached trusted SelfSteal certificate')).toContain('Le_TLSPort')
    expect(taskBlock('Verify the fallback HTTP-01 route through Nginx')).toContain('status_code: 200')
    expect(taskBlock('Verify the fallback HTTP-01 route through Nginx')).toContain("Host: '{{ node_fqdn }}'")
    expect(taskBlock('Verify the fallback HTTP-01 route through Nginx')).toContain('failed_when: false')
    expect(taskBlock('Verify the fallback HTTP-01 route through Nginx')).toContain('use_proxy: false')
    expect(taskBlock('Verify the fallback HTTP-01 route from the provisioning worker')).toContain('delegate_to: localhost')
    expect(taskBlock('Verify the fallback HTTP-01 route from the provisioning worker')).toContain('failed_when: false')
    expect(issueTask).toContain("- '{{ selfsteal_dir }}/html'")
    expect(issueTask).toContain('- timeout')
    expect(issueTask).toContain("- '{{ acme_issue_timeout_seconds | string }}'")
    expect(issueTask).toContain('- ec-256')
    expect(issueTask).not.toContain('--alpn')
    expect(issueTask).not.toContain('--tlsport')
    expect(issueTask).toContain('- cached_selfsteal_certificate.rc != 0')
    expect(issueTask).toContain('failed_when: false')
    expect(taskBlock('Stage the trusted certificate without reloading Nginx')).toContain('- --install-cert')
    expect(taskBlock('Stage the trusted certificate without reloading Nginx')).toContain('- --ecc')
    expect(taskBlock('Stage the trusted certificate without reloading Nginx')).toContain('- /bin/true')
    expect(taskBlock('Validate the staged certificate and private key')).toContain('-checkhost')
    const preparePair = taskBlock('Prepare the SelfSteal certificate pair for atomic deployment')
    const installPair = taskBlock('Install the staged SelfSteal certificate pair transactionally')
    expect(preparePair).toContain('private.key.pending')
    expect(preparePair).toContain('private.key.previous')
    expect(preparePair).toContain('install -o root -g root -m 0600 "$staged_key" "$pending_key"')
    expect(preparePair.split('\n        - name: Stop SelfSteal')[0]).not.toContain('no_log: true')
    expect(installPair).toContain('restore_previous_pair')
    expect(installPair).toContain("trap 'rc=$?")
    expect(installPair).toContain("trap 'exit 143' TERM")
    expect(installPair).toContain('Certificate deployment failed; restoring the previous SelfSteal pair')
    expect(installPair).toContain('mv -fT -- "$pending_key" "$live_key"')
    expect(installPair).toContain('mv -fT -- "$pending_cert" "$live_cert"')
    expect(installPair.split('\n      always:')[0]).not.toContain('no_log: true')
    expect(taskBlock('Deploy the trusted SelfSteal certificate from a validated staging area'))
      .toContain('selfsteal_certificate_needs_deployment')
    expect(playbook.indexOf('Issue the trusted SelfSteal certificate through the fallback HTTP webroot'))
      .toBeLessThan(playbook.indexOf('Validate the certificate hostname'))
    expect(renewalWrapper).toContain('set -euo pipefail')
    expect(renewalWrapper).toContain('certificate_key_fingerprint')
    expect(taskBlock('Validate automatic SelfSteal certificate renewal')).toContain('- --check')
  })

  it('uses direct port 443 TLS-ALPN and renews independently of legacy ACME metadata', () => {
    const directIssue = taskBlock('Request the trusted SelfSteal certificate through direct TLS-ALPN')
    expect(taskBlock('Stop Remnanode while the direct ACME listener owns port 443')).toContain('- remnanode')
    expect(directIssue).toContain('- --alpn')
    expect(directIssue).toContain('- timeout')
    expect(directIssue).toContain("- '443'")
    expect(directIssue).toContain('failed_when: false')
    expect(taskBlock('Start Remnanode after the direct ACME attempt')).toContain('- docker')
    expect(taskBlock('Stop when both trusted certificate challenges failed')).toContain('HTTP result:')
    expect(taskBlock('Stop when both trusted certificate challenges failed')).toContain('Direct TLS result:')
    expect(taskBlock('Stop when both trusted certificate challenges failed')).toContain('Public HTTP preflight:')
    expect(taskBlock('Stop when both trusted certificate challenges failed')).toContain('HTTP diagnostics:')
    expect(taskBlock('Collect SelfSteal HTTP diagnostics')).toContain("ss -ltnp '( sport = :80 )'")
    expect(playbook.indexOf('Issue the trusted SelfSteal certificate directly on port 443'))
      .toBeLessThan(playbook.indexOf('Issue the trusted SelfSteal certificate through the fallback HTTP webroot'))
    expect(renewalWrapper).toContain('trap cleanup EXIT INT TERM')
    expect(renewalWrapper).toContain('docker stop remnanode')
    expect(renewalWrapper).toContain('docker start remnanode')
    expect(renewalWrapper).toContain('--issue --domain "$DOMAIN"')
    expect(renewalWrapper).toContain('--keylength ec-256')
    expect(renewalWrapper).toContain('--alpn --tlsport 443')
    expect(renewalWrapper).toContain('port_443_is_free=false')
    expect(renewalWrapper).toContain('timeout --signal=TERM --kill-after=10s')
    expect(renewalWrapper).toContain('--install-cert --domain "$DOMAIN"')
    expect(renewalWrapper).toContain('--ecc')
    expect(renewalWrapper).toContain('SELFSTEAL_RENEW_STAGE_DIR:-/run/selfsteal-cert-renew')
    expect(renewalWrapper).toContain('--reloadcmd /bin/true')
    expect(renewalWrapper).toContain('docker compose --project-directory "$SELFSTEAL_DIR" down')
    expect(renewalWrapper).toContain('docker compose --project-directory "$SELFSTEAL_DIR" up')
    expect(renewalWrapper).toContain('install_certificate_pair')
    expect(renewalWrapper).toContain('restore_previous_pair')
    expect(renewalWrapper).toContain('docker exec nginx-selfsteal nginx -t')
    expect(renewalWrapper).toContain("if [ \"${1:-}\" = '--check' ]")
    expect(renewalWrapper).toContain('-checkhost "$DOMAIN"')
    expect(renewalWrapper).not.toContain('domain_conf')
    expect(renewalWrapper).not.toContain('Le_Webroot')
  })

  it('treats a restarting SelfSteal container as resumable and waits for stability', () => {
    const state = taskBlock('Determine the current SelfSteal state')
    expect(state).toContain("docker-compose.yml|true|false")
    expect(taskBlock('Stop an owned unstable SelfSteal container before recovery')).toContain('selfsteal_is_resumable')
    expect(taskBlock('Remove the stale SelfSteal Unix socket before recovery')).toContain('/dev/shm/nginx.sock')
    expect(taskBlock('Wait for SelfSteal to remain stable')).toContain('stable_checks')
    expect(taskBlock('Wait for SelfSteal to remain stable')).toContain('restarting=false')
    expect(taskBlock('Wait for SelfSteal after certificate deployment')).toContain('docker logs --tail 100')
    expect(renewalWrapper).toContain('rm -f /dev/shm/nginx.sock')
  })

  it('does not fail an otherwise healthy node only because port 80 has no redirect', () => {
    expect(worker).toContain("return `HTTP redirect недоступен (${redirect.status}), VPN и HTTPS работают`")
    expect(worker).toContain("return 'HTTP redirect недоступен, VPN и HTTPS работают'")
    expect(worker).toContain("addEvent(jobId, 'VERIFY', 'WARNING', verificationWarning)")
  })

  it('keeps the UFW assertion a string for Ansible 2.19', () => {
    expect(playbook).toContain(`- "'Status: active' in final_ufw_status.stdout"`)
    expect(playbook).not.toContain("- final_ufw_status.stdout is search('Status: active')")
  })
})
