ALTER TYPE "BroadcastDeliveryStatus" ADD VALUE 'UNKNOWN';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_BROADCAST_RETRIED';

ALTER TABLE "BroadcastCampaign"
  ADD COLUMN "telegramUnknown" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "emailUnknown" INTEGER NOT NULL DEFAULT 0;
